plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.1.cjs
npmAuthToken: ${AUTH_TOKEN:-fallback}
