name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish-eslint-config:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --immutable

      - run: yarn workspace @nzws/eslint-config npm publish
        env:
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-prettier-config:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --immutable

      - run: yarn workspace @nzws/prettier-config npm publish
        env:
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
